language: python

matrix:
  include:
    - python: 3.5
      env: PYDATAENV=py35
    - python: 3.6
      env: PYDATAENV=py36

install:
  - pip install pydata
  - pip install coveralls

script:
  - pydata
  - coverage run --source=pydata setup.py test

notifications:
  email: false

after_success:
  - coveralls
